### ISSUE TITLE
Adding 'Clear' button to coordinate dialog

### ISSUE THREAD

**Issue by fedriani** [starhunt-project/starhunt-web-client#29]
@pkgw, can we add here a similar code that the one for 'Copy to Clipboard'? also modifying StarHuntControllers.js in a similar way? is it just changing execCommand('copy')  to execCommand('delete')

https://github.com/starhunt-project/starhunt-web-client/blob/3215f084f1aa8b877321514a7fea0325624e5dd0/views/modals/starhunt-marker-report.html#L6-L10

https://github.com/starhunt-project/starhunt-web-client/blob/3215f084f1aa8b877321514a7fea0325624e5dd0/controllers/StarHuntController.js#L288-L302

I prefer asking than mess everything up.

PS: I am still getting used to working with GitHub, please let me know if this is the usual way to comment, work, and do things in general. Thanks

**Comment by pkgw** [comment]
Starting with your "PS", yes, this is a good way to raise this kind of question and discuss potential solutions. It's better than email since the discussion is archived publicly and connected to the relevant code.

The overall framework of adding a "clear" button would be analogous to how the copy button works, but the particular `document.execCommand('copy')` function is a special hook provided by the web browser that copies the current text selection to the user's clipboard. Clearing the markers doesn't have anything to do with the clipboard, so the implementation will be different.

To figure out the best implementation strategy we'll have to get a bit more specific. Do you want a Clear button to delete from the WWT view? Or just for fewer markers to appear in the text box that pops up?

Finally, remember that thanks to the fact that we use Git and we have a local testing capability, you can always create a new Git branch of the code for experimentation and throw it away if what you try didn't work. The ability to safely experiment with unfinished ideas, secure in the knowledge that you can get back to the known-good code if they don't work out, is one of Git's most important benefits.

**Comment by fedriani** [comment]
I meant clear the coordinates from the text box, keeping the markers on the screen.

However, this is something that needs to be discussed, I am not sure what Jonathan has in mind and if we actually need this feature.

Let's call this in pause and I will let you know if there is any update.

**Comment by fedriani** [comment]
Ok, now I think we have a good idea of what we need:

The idea is just to get rid of the coordinates from the clipboard, keeping the markers. The reason is that we are placing coordinates markers for two different astronomical objects. On the one hand, we are locating filaments, and on the other hand, we are locating bubbles.

In this way, we will be placing markers on the dark filaments of the IRDCs, retrieving the coordinates, and pasting into Table 1 (filament stuff). Then (keeping the markers of the filaments), we will be placing markers on the bubbles (probably HII region in the star formation site), retrieve only 'bubble' coordinates, and then paste into Table 2 (bubble stuff).

Is it clear what is the idea here? We can have a quick zoom meeting if needed. Thanks! @pkgw
