### ISSUE TITLE
Changing RA (HH:MM:SS) and DEC(DD:MM:SS) to RA and dec in degrees

### ISSUE THREAD

**Issue by fedriani** [starhunt-project/starhunt-web-client#37]
Hello @pkgw ,

I have been trying to work locally with the webpage, but failed...
The previous version was up (the one with just the initial tools), so I updated it. Bu the previous version was still the one running and not the 'updated'. So I downloaded it again and run the commands that are written in the README. The _npm_ command seemed to work fine, but when I run the _grunt_ command, the following appeared:

'''
> grunt dist-all

Running "gitinfo" task

Running "concat:webclient" (concat) task
Warning: An error occurred while processing a template (Cannot read property 'branch' of undefined). Use --force to continue.

Aborted due to warnings.
'''

I did not want to bother you, but I think it will take you a second to change the coordinate issue and I was not sure how to do it (and again did not want to mess up everything). Let me explain you quickly:

We found out that when dealing with coordinates in hours minutes and seconds, the students get very confused. Moreover, when dealing with the coordinates in the excel files we have prepared for them, the spreadsheet gets confused with the format (even though we have defined a custom format...). So, Jonathan, Giuliana, and I have decided that the easiest is just to deal with RA and DEC in degrees, so we will have 'normal' numbers.

I think, we just need to modify the lines below based on Utils.js, but was not sure what function to use.

https://github.com/starhunt-project/starhunt-web-client/blob/ce61b65b0691ad16ccbeeaff6ad04035c3bb1c1f/controllers/StarHuntController.js#L285-L287

Once again, thanks a million @pkgw 
Rubén

**Comment by pkgw** [comment]
Hmmm, if I reset my repository and rebuild from scratch, I don't get any errors. It seems that the "gitinfo" step is not successfully getting up the variables needed for the templating stage, but I can't figure out why it might be failing for you. Maybe try running `npm install -g grunt` and then retry the setup?

As for using decimal degrees, that makes sense. To format numbers that way, you should use this function in the JavaScript standard library: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

If we can't straighten out your build setup, I can make the change myself, but we should see if we can get you going again since the build process should be straightforward.

**Comment by fedriani** [comment]
Hi @pkgw ,

Sorry for the late reply, it has been a busy week. I managed to make it work. I was trying to duplicate the repository in a folder where the 'old' repository was. I did not want to delete it just in case I messed up with the new one. I think the 'new' repository got confused and never built. So, what I did was to go to my  Desktop folder and clone the repo there and build everything from scratch. Obviously, as you anticipated, it worked. I could make a few changes, experiment and finally change the coordinates format, which turned out to be pretty simple.

I will call this closed and that should be it, no more changes! (but one never knows!)

All the best,
Rubén
